update

diff --git a/plotting/plot/do-all b/plotting/plot/do-all
--- a/plotting/plot/do-all
+++ b/plotting/plot/do-all
@@ -10,7 +10,14 @@ for script in `ls | grep do-`; do
         continue
     fi
     echo "############################"
+    >&2 echo "Starting $script"
     echo $script
     time ./$script
+    if [ $? -eq 0 ]; then
+        >&2 echo "$script SUCCESS"
+    else
+        >&2 echo "$script FAILURE"
+    fi
+
 done
 echo "DONE! :-)"
